# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

url: "https://wabinab.github.io"

title: Here we go!
description: Blogging and Projects hosting. 
github_username: Wabinab

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

repository: Wabinab/Wabinab.github.io

# Everything below here can be ignored, unless you want to change the theme entirely
theme: # minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-target-blank
  - kramdown-syntax-coderay

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: coderay  #rouge
  
target-blank:
    rel: nofollow

header_page_refs: ['about']
